### ISSUE TITLE
How can i use this tool

### ISSUE THREAD

**Issue by Ugroon** [Antwns/AntCrypter#1]
Dude i can't find main crypter file

**Comment by Antwns** [comment]
> Dude i can't find main crypter file

Please explain by what you mean "main crypter file"?

If you want the source code you download the source code.
If you want a program running out of the box, you download the release.

Ps.I must inform you that this crypter is no longer FUD as many AVs have downloaded the code. If you attempt to compile any viruses they won't be hidden/undetecable.

**Comment by Antwns** [comment]
@Ugroon I haven't heard back from you so I'm closing this thread
